package model

enum class Rating {
    GENERAL, TEEN, MATURE, EXPLICIT, NONE
}

enum class Category {
    GEN, FEMALE_MALE, MALE_MALE, FEMALE_FEMALE, MULTI, OTHER, NONE
}

enum class Warning {
    NO_WARNINGS, CREATOR_CHOSE_NOT_TO_USE_WARNINGS, GRAPHIC_VIOLENCE, MAJOR_CHARACTER_DEATH, RAPE, UNDERAGE
}

enum class SortOrder {
    AUTHOR, TITLE, DATE_POSTED, DATE_UPDATED, WORD_COUNT, HITS, KUDOS, COMMENTS, BOOKMARKS
}
